---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  # - name: centos-6.4

suites:
  - name: uptime
    run_list:
      - 'recipe[apt]'
      - 'recipe[uptime]'
    attributes:
      app_uptime:
        mongo:
          password: PLEASESETYOUROWNPASSWORD
